### ISSUE TITLE
rx-drawn cursor is frozen and system cursor is invisible when over an inactive rx window

### ISSUE THREAD

**Issue by ssokolow** [cloudhead/rx#80] opened 2020-05-10 00:31 UTC
On rx 0.4.0, if rx loses focus, all window updates will stop, which makes sense as a way to avoid waste... but the cursor drawn by rx also freezes.

It seems reasonable that, when rx loses window focus, it should temporarily undo "hide the system cursor while over this window so we can draw our own".

**Comment by cloudhead** [comment] 2020-05-10 08:39
Ah interesting. Since I use a tiling window manager which focuses the window on hover, I haven't seen this happen. So the problem is that even though the rx window is inactive, it still hides the system cursor when it is above the window.

**Comment by cloudhead** [comment] 2020-05-10 08:55
I've attempted a fix here in the `fix/issue-80` branch. Could you try it out?

**Comment by ssokolow** [comment] 2020-05-11 02:21
Sure. I was too busy today, but I'll try to fit it in tomorrow.

**Comment by ssokolow** [comment] 2020-05-11 18:29
It's not perfect, but it's a good enough fix for me.

(It has the same problem that causes accessibility issues for people with visual impairment with Snaps on Ubuntu... it ignores the user's system cursor theme, so my cursor changes from black with a white border to white with a black border when it crosses into an inactive rx window.)

**Comment by cloudhead** [comment] 2020-05-13 22:19
Great. I'm unlikely to have a solution for the other problem that works cross-platform.

**Comment by cloudhead** [comment] 2020-05-13 22:21
Fixed in de545c1

**Closed by cloudhead** 2020-05-13 22:21 UTC
Labels: type:bug
